# Generated by Django 4.2 on 2023-04-28 18:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('do_zrobienia', 'Do_zrobienia'), ('w_trakcie', 'W_trakcie'), ('zrobione', 'Zrobione')], default='do_zrobienia', max_length=20)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
